import { spawn } from 'child_process';
import { app, BrowserWindow, ipcMain, protocol, session } from 'electron';
import * as path from 'path';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// protocol.registerSchemesAsPrivileged([
//   {
//     scheme: "app",
//     privileges: {
//       standard: true,
//       secure: true,
//       supportFetchAPI: true,
//       corsEnabled: true
//     }
//   }
// ])

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

ipcMain.handle("process-image", async (event, imagePath) => {
  console.log("Processing image at path: ", imagePath.slice(0, 10)); // Log the first 100 characters of the image path for debugging
  // Here you would add your image processing logic. For demonstration, we'll just return the same path.
  const filePath = await saveImage(imagePath);

  return new Promise((resolve, reject) => {

    const py = spawn("python3", [
      path.join(app.getAppPath(), "python-engine/main.py"),
      filePath
    ])

    py.stdout.on("data", (data) => {
      const outputPath = data.toString().trim();
      resolve(outputPath);
    })

    py.stderr.on("data", (err) => {
      console.error("Error from Python script: ", err.toString());
      reject(err.toString());
    })

  })

  return filePath;
})

function saveImage(imageData: string): string {
  const buffer = Buffer.from(imageData.split(',')[1], 'base64');
  const filePath = `uploads/processed_image_${Date.now()}.png`;
  require('fs').writeFileSync(filePath, buffer);
  return filePath;
}

// Simulate saving the image and returning the path

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

app.whenReady().then(() => {

  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    callback({
      responseHeaders: {
        ...details.responseHeaders,
        "Content-Security-Policy": [
          "default-src 'self'; img-src 'self' data: app:; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'"
        ]
      }
    })
  })


  protocol.handle("app", async (request) => {
    const url = request.url.replace("app://", "")
    const filePath = path.join(app.getAppPath(), url)

    console.log("protocol file path:", filePath)

    return new Response(require("fs").createReadStream(filePath))
  })
})